### ISSUE TITLE
multi bars after file/save

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_breadcrumbs#16]
![bug](https://user-images.githubusercontent.com/4154978/124493451-51c01680-ddbe-11eb-99e8-3841aba94e5d.png)

```
Python 3.8.10
Init: cuda_breadcrumbs
Loaded session: "history session.json", 0ms, 0 file(s)
Startup: 160ms, plugins: 20ms (breadcrumbs 20ms)
Init: cuda_fmt
Formatters: XML, XML ^, regex:JSON.*, regex:JavaScript.*
Init: cuda_console_complete
Init: cuda_hilite_occurrences
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 163, in on_save
    bc.on_save()
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 349, in on_save
    self.reset()
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 262, in reset
    self._path_items.clear()
AttributeError: 'tuple' object has no attribute 'clear'
ERROR: Exception in CudaText for on_save: AttributeError: 'tuple' object has no attribute 'clear'
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 163, in on_save
    bc.on_save()
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 349, in on_save
    self.reset()
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 262, in reset
    self._path_items.clear()
AttributeError: 'tuple' object has no attribute 'clear'
ERROR: Exception in CudaText for on_save: AttributeError: 'tuple' object has no attribute 'clear'
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 163, in on_save
    bc.on_save()
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 349, in on_save
    self.reset()
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 262, in reset
    self._path_items.clear()
AttributeError: 'tuple' object has no attribute 'clear'
ERROR: Exception in CudaText for on_save: AttributeError: 'tuple' object has no attribute 'clear'
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 163, in on_save
    bc.on_save()
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 349, in on_save
    self.reset()
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 262, in reset
    self._path_items.clear()
AttributeError: 'tuple' object has no attribute 'clear'
ERROR: Exception in CudaText for on_save: AttributeError: 'tuple' object has no attribute 'clear'
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 163, in on_save
    bc.on_save()
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 349, in on_save
    self.reset()
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 262, in reset
    self._path_items.clear()
AttributeError: 'tuple' object has no attribute 'clear'
ERROR: Exception in CudaText for on_save: AttributeError: 'tuple' object has no attribute 'clear'
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 163, in on_save
    bc.on_save()
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 349, in on_save
    self.reset()
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 262, in reset
    self._path_items.clear()
AttributeError: 'tuple' object has no attribute 'clear'
ERROR: Exception in CudaText for on_save: AttributeError: 'tuple' object has no attribute 'clear'
Init: cudatext
```

**Comment by halfbrained** [comment]
Fixed, sorry, that was a brainfart :)
