### ISSUE TITLE
ERROR: Exception in CudaText for on_cell_click: StopIteration

### ISSUE THREAD

**Issue by JairoMartinezA** [halfbrained/cuda_breadcrumbs#27]
Looking for steps to repro.

    Python 3.6.8

    Traceback (most recent call last):
      File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cuda_breadcrumbs\breadcrumbs.py", line 220, in on_cell_click
        bread.on_click(cell_ind)
      File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cuda_breadcrumbs\breadcrumbs.py", line 375, in on_click
        self.tree.show_dir(fn=path.as_posix(), root=_parent, btn_rect=btn_rect)
      File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cuda_breadcrumbs\dlg.py", line 97, in show_dir
        self.data = load_filepath_tree(fn, root)
      File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cuda_breadcrumbs\dlg.py", line 214, in load_filepath_tree
        item = next(it for it in item.children  if it.name == name)
    StopIteration
    ERROR: Exception in CudaText for on_cell_click: StopIteration

**Comment by JairoMartinezA** [comment]
Another error, pending steps:

    ERROR: statusbar_proc() gets bad handle of type TFormDummy
    TypeError: an integer is required (got type NoneType)

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cuda_breadcrumbs\breadcrumbs.py", line 173, in on_open
        bc.on_fn_change()
      File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cuda_breadcrumbs\breadcrumbs.py", line 410, in on_fn_change
        self.update()
      File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cuda_breadcrumbs\breadcrumbs.py", line 318, in update
        self._update_bgs(len(path_items),  len(code_items),  _n_prefix)
      File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cuda_breadcrumbs\breadcrumbs.py", line 424, in _update_bgs
        statusbar_proc(self.h_sb, STATUSBAR_SET_CELL_AUTOSIZE, index=ind, value=True)
      File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cudatext.py", line 1138, in statusbar_proc
        return ct.statusbar_proc(str(id_statusbar), id_action, index, tag, to_str(value))
    SystemError: <built-in function statusbar_proc> returned a result with an error set
    ERROR: Exception in CudaText for on_open: SystemError: <built-in function statusbar_proc> returned a result with an error set

**Comment by Alexey-T** [comment]
ERROR: statusbar_proc() gets bad handle of type TFormDummy
TypeError: an integer is required (got type NoneType)

thet is clearly the plugin error.

**Comment by halfbrained** [comment]
I fixed a few issues. Yours are both weird ones, but there is a good change they will go away now :)

**Comment by Alexey-T** [comment]
@JairoMartinezA Pls test last version of plugin
