### ISSUE TITLE
console-errors on starting with 2-files tab (user/default)

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_breadcrumbs#33]
![Screenshot from 2021-07-07 18-21-45](https://user-images.githubusercontent.com/4154978/124786184-3127c600-df50-11eb-8e14-bdadcbfbc90e.png)

```
Python 3.8.10
Init: cuda_breadcrumbs
Init: cuda_hilite_occurrences
Loaded session: "history session.json", 20ms, 2 file(s)
Startup: 180ms, plugins: 30ms (breadcrumbs 21ms, hilite_occurrences 17ms)
Init: cudatext
TypeError: an integer is required (got type NoneType)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 236, in on_cell_click
    bread.on_click(cell_ind)
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 432, in on_click
    self.tree.show_dir(fn=str(path),  root=_parent,  btn_rect=btn_rect,  h_ed=self.ed.h)
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/dlg.py", line 108, in show_dir
    tree_proc(self.h_tree, TREE_ITEM_SELECT, id_item=sel_item.id)
  File "/home/user/.config/cudatext/py/cudatext.py", line 1110, in tree_proc
    return ct.tree_proc(id_tree, id_action, id_item, index, to_str(text), image_index, data)
SystemError: <built-in function tree_proc> returned a result with an error set
ERROR: Exception in CudaText for on_cell_click: SystemError: <built-in function tree_proc> returned a result with an error set
ERROR: Exception in CudaText for cudatext._dlg_proc_callback_proxy: Access violation
TypeError: an integer is required (got type NoneType)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 236, in on_cell_click
    bread.on_click(cell_ind)
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 432, in on_click
    self.tree.show_dir(fn=str(path),  root=_parent,  btn_rect=btn_rect,  h_ed=self.ed.h)
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/dlg.py", line 108, in show_dir
    tree_proc(self.h_tree, TREE_ITEM_SELECT, id_item=sel_item.id)
  File "/home/user/.config/cudatext/py/cudatext.py", line 1110, in tree_proc
    return ct.tree_proc(id_tree, id_action, id_item, index, to_str(text), image_index, data)
SystemError: <built-in function tree_proc> returned a result with an error set
ERROR: Exception in CudaText for on_cell_click: SystemError: <built-in function tree_proc> returned a result with an error set
ERROR: Exception in CudaText for on_cell_click: Access violation
TypeError: an integer is required (got type NoneType)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 236, in on_cell_click
    bread.on_click(cell_ind)
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 432, in on_click
    self.tree.show_dir(fn=str(path),  root=_parent,  btn_rect=btn_rect,  h_ed=self.ed.h)
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/dlg.py", line 108, in show_dir
    tree_proc(self.h_tree, TREE_ITEM_SELECT, id_item=sel_item.id)
  File "/home/user/.config/cudatext/py/cudatext.py", line 1110, in tree_proc
    return ct.tree_proc(id_tree, id_action, id_item, index, to_str(text), image_index, data)
SystemError: <built-in function tree_proc> returned a result with an error set
ERROR: Exception in CudaText for on_cell_click: SystemError: <built-in function tree_proc> returned a result with an error set
ERROR: Exception in CudaText for on_cell_click: Access violation
TypeError: an integer is required (got type NoneType)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 236, in on_cell_click
    bread.on_click(cell_ind)
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/breadcrumbs.py", line 432, in on_click
    self.tree.show_dir(fn=str(path),  root=_parent,  btn_rect=btn_rect,  h_ed=self.ed.h)
  File "/home/user/.config/cudatext/py/cuda_breadcrumbs/dlg.py", line 108, in show_dir
    tree_proc(self.h_tree, TREE_ITEM_SELECT, id_item=sel_item.id)
  File "/home/user/.config/cudatext/py/cudatext.py", line 1110, in tree_proc
    return ct.tree_proc(id_tree, id_action, id_item, index, to_str(text), image_index, data)
SystemError: <built-in function tree_proc> returned a result with an error set
ERROR: Exception in CudaText for on_cell_click: SystemError: <built-in function tree_proc> returned a result with an error set
```

**Comment by Alexey-T** [comment]
repro!!

make narrow window. 
click the cell which is overflowed to the left!

here it is 'config' cell
![Screenshot from 2021-07-07 18-23-50](https://user-images.githubusercontent.com/4154978/124786658-924f9980-df50-11eb-8561-7e45d96cf0a3.png)

**Comment by Alexey-T** [comment]
repro 2.
just click on '.config' cell w/o overflow.

**Comment by halfbrained** [comment]
Do you have option `show_hidden_files` disabled?

**Comment by Alexey-T** [comment]
```
[breadcrumbs]
root_dir_source=0
show_root_parents=1
file_sort_type=ext
tilde_home=1
show_hidden_files=0
max_name_len=15
max_dirs_count=0
position_bottom=1
```

**Comment by halfbrained** [comment]
Should be good now
